# Generated by Django 5.1.4 on 2025-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0004_remove_post_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatars',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
