# Generated by Django 5.1.5 on 2025-01-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0007_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
